In [1]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('/content/drive/My Drive/ШКОЛА ММ/data.csv', encoding = 'utf-8')

data = pd.DataFrame(data)

Mounted at /content/drive

In [2]:
data

,Город,Аэропорт,Достопремечательность,Удаленность,Время_на_посещение,Время_С,Время_ДО,Стоимость,Можно с детьми,Активность,Место,Популярность
0,Москва,Шереметьево,Завод чистая линия,1.0,1.5,9,18,2400,да,Экскурсия,Помещение,7
1,Москва,Шереметьево,Московский зоопарк,1.0,2.0,9,20,800,да,Прогулка,Улица,1
2,Москва,Шереметьево,Красная площадь,1.2,1.5,10,18,0,да,Прогулка,Улица,0
3,Москва,Шереметьево,Музей советских игровых автоматов,1.5,1.5,9,19,500,да,Экскурсия,Помещение,5
4,Москва,Шереметьево,Кремль в Измайлово,1.8,1.5,9,21,0,да,Прогулка,Улица,3
5,Москва,Шереметьево,Воробьевы горы,2.3,2.0,0,24,0,да,Прогулка,Улица,2
6,Москва,Шереметьево,Усадьба Марфино,1.4,1.5,9,17,0,да,Прогулка,Улица,6
7,Москва,Шереметьево,Экскурсия на теплоходе,1.8,1.5,15,20,1200,да,Экскурсия,Улица,4
8,Москва,Шереметьево,"Ресторан ""Марко Поло""",0.5,1.0,11,22,500,да,Питание,Помещение,8
9,Москва,Шереметьево,"Ресторан ""Венеция""",0.5,1.0,12,24,750,да,Питание,Помещение,8
10,Москва,Шереметьево,"Ресторан ""Якитория""",1.4,1.0,11,24,1500,да,Питание,Помещение,8
11,Москва,Шереметьево,"Ресторан ""Сан Ремо""",1.1,1.0,12,23,1000,да,Питание,Помещение,8
12,Москва,Шереметьево,"Ресторан ""Ti Amo""",0.7,1.0,10,23,500,да,Питание,Помещение,8
13,Москва,Шереметьево,"Ресторан ""Попугай""",1.3,1.0,11,23,700,да,Питание,Помещение,8
14,Москва,Шереметьево,"Отель ""Юность""",0.5,8.0,0,24,2000,да,Сон,Помещение,9
15,Москва,Шереметьево,"Отель ""Спартак""",0.7,8.0,0,24,2000,да,Сон,Помещение,9
16,Москва,Шереметьево,"Отель ""Holiday Inn""",1.1,8.0,0,24,4000,да,Сон,Помещение,9
17,Москва,Шереметьево,"Кинотеатр ""Чайка""",0.5,1.5,10,1,350,да,Кино,Помещение,10
18,Москва,Шереметьево,"Кинотеатр ""Галакс""",1.0,1.5,10,22,300,да,Кино,Помещение,10
19,Москва,Шереметьево,"Кинотеатр ""Синема парк""",1.0,1.5,10,22,400,да,Кино,Помещение,10

In [ ]:
data.pop('Город')
data.pop('Аэропорт')
data.pop('Можно с детьми')

In [4]:
import random

dost = list(data['Достопремечательность'])
data_new = pd.DataFrame()

for i in range(1,11):
  for j in dost:
    new_row = {'Юзер':i,
               'Достопремечательность':j,
               'Оценка':random.choice([' ', 1, 2, 3, 4, 5])}
    data_new = data_new.append(new_row, ignore_index=True)

In [5]:
data_new

     Юзер              Достопремечательность Оценка
0     1.0                 Завод чистая линия    5.0
1     1.0                 Московский зоопарк    5.0
2     1.0                    Красная площадь    2.0
3     1.0  Музей советских игровых автоматов    4.0
4     1.0                 Кремль в Измайлово    3.0
..    ...                                ...    ...
195  10.0                    Отель "Спартак"      1
196  10.0                Отель "Holiday Inn"      4
197  10.0                  Кинотеатр "Чайка"      5
198  10.0                 Кинотеатр "Галакс"      2
199  10.0            Кинотеатр "Синема парк"      4

[200 rows x 3 columns]

In [6]:
full_data = pd.merge(data_new, data, on='Достопремечательность')

In [7]:
full_data.convert_dtypes() 
full_data

,Юзер,Достопремечательность,Оценка,Удаленность,Время_на_посещение,Время_С,Время_ДО,Стоимость,Активность,Место,Популярность
0,1.0,Завод чистая линия,5.0,1.0,1.5,9,18,2400,Экскурсия,Помещение,7
1,2.0,Завод чистая линия,5,1.0,1.5,9,18,2400,Экскурсия,Помещение,7
2,3.0,Завод чистая линия,4,1.0,1.5,9,18,2400,Экскурсия,Помещение,7
3,4.0,Завод чистая линия,,1.0,1.5,9,18,2400,Экскурсия,Помещение,7
4,5.0,Завод чистая линия,5,1.0,1.5,9,18,2400,Экскурсия,Помещение,7
...,...,...,...,...,...,...,...,...,...,...,...
195,6.0,"Кинотеатр ""Синема парк""",,1.0,1.5,10,22,400,Кино,Помещение,10
196,7.0,"Кинотеатр ""Синема парк""",1,1.0,1.5,10,22,400,Кино,Помещение,10
197,8.0,"Кинотеатр ""Синема парк""",,1.0,1.5,10,22,400,Кино,Помещение,10
198,9.0,"Кинотеатр ""Синема парк""",2,1.0,1.5,10,22,400,Кино,Помещение,10
199,10.0,"Кинотеатр ""Синема парк""",4,1.0,1.5,10,22,400,Кино,Помещение,10

In [ ]:
full_data = full_data.loc[full_data['Оценка'] != ' ']
full_data['Оценка'] = full_data['Оценка'].astype(int)
full_data['Юзер'] = full_data['Юзер'].astype(int)

In [9]:
full_data.dtypes

Юзер                       int64
Достопремечательность     object
Оценка                     int64
Удаленность              float64
Время_на_посещение       float64
Время_С                    int64
Время_ДО                   int64
Стоимость                  int64
Активность                object
Место                     object
Популярность               int64
dtype: object

In [10]:
# Средний рейтинг каждого места
full_data.groupby('Достопремечательность')['Оценка'].mean()

Достопремечательность
Воробьевы горы                       2.666667
Завод чистая линия                   3.777778
Кинотеатр "Галакс"                   2.125000
Кинотеатр "Синема парк"              2.625000
Кинотеатр "Чайка"                    2.888889
Красная площадь                      2.500000
Кремль в Измайлово                   3.625000
Московский зоопарк                   3.500000
Музей советских игровых автоматов    2.500000
Отель "Holiday Inn"                  3.333333
Отель "Спартак"                      2.400000
Отель "Юность"                       2.857143
Ресторан "Ti Amo"                    3.222222
Ресторан "Венеция"                   3.142857
Ресторан "Марко Поло"                2.900000
Ресторан "Попугай"                   3.777778
Ресторан "Сан Ремо"                  2.777778
Ресторан "Якитория"                  4.000000
Усадьба Марфино                      2.625000
Экскурсия на теплоходе               3.375000
Name: Оценка, dtype: float64

In [11]:
# Отсортированный средний рейтинг каждого места
full_data.groupby('Достопремечательность')['Оценка'].mean().sort_values(ascending=False)

Достопремечательность
Ресторан "Якитория"                  4.000000
Ресторан "Попугай"                   3.777778
Завод чистая линия                   3.777778
Кремль в Измайлово                   3.625000
Московский зоопарк                   3.500000
Экскурсия на теплоходе               3.375000
Отель "Holiday Inn"                  3.333333
Ресторан "Ti Amo"                    3.222222
Ресторан "Венеция"                   3.142857
Ресторан "Марко Поло"                2.900000
Кинотеатр "Чайка"                    2.888889
Отель "Юность"                       2.857143
Ресторан "Сан Ремо"                  2.777778
Воробьевы горы                       2.666667
Кинотеатр "Синема парк"              2.625000
Усадьба Марфино                      2.625000
Музей советских игровых автоматов    2.500000
Красная площадь                      2.500000
Отель "Спартак"                      2.400000
Кинотеатр "Галакс"                   2.125000
Name: Оценка, dtype: float64

In [12]:
# Общее кол-во оценок для каждого места
full_data.groupby('Достопремечательность')['Оценка'].count().sort_values(ascending=False)

Достопремечательность
Отель "Спартак"                      10
Красная площадь                      10
Ресторан "Марко Поло"                10
Ресторан "Ti Amo"                     9
Кинотеатр "Чайка"                     9
Ресторан "Сан Ремо"                   9
Ресторан "Попугай"                    9
Отель "Holiday Inn"                   9
Завод чистая линия                    9
Усадьба Марфино                       8
Ресторан "Якитория"                   8
Экскурсия на теплоходе                8
Музей советских игровых автоматов     8
Московский зоопарк                    8
Кремль в Измайлово                    8
Кинотеатр "Синема парк"               8
Кинотеатр "Галакс"                    8
Отель "Юность"                        7
Ресторан "Венеция"                    7
Воробьевы горы                        3
Name: Оценка, dtype: int64

In [13]:
# Матрица названий фильмов и соответствующих пользовательских оценок
Name_User_Rat = full_data.pivot_table(index='Юзер', columns='Достопремечательность', values='Оценка')
Name_User_Rat

Достопремечательность,Воробьевы горы,Завод чистая линия,"Кинотеатр ""Галакс""","Кинотеатр ""Синема парк""","Кинотеатр ""Чайка""",Красная площадь,Кремль в Измайлово,Московский зоопарк,Музей советских игровых автоматов,"Отель ""Holiday Inn""","Отель ""Спартак""","Отель ""Юность""","Ресторан ""Ti Amo""","Ресторан ""Венеция""","Ресторан ""Марко Поло""","Ресторан ""Попугай""","Ресторан ""Сан Ремо""","Ресторан ""Якитория""",Усадьба Марфино,Экскурсия на теплоходе
Юзер,,,,,,,,,,,,,,,,,,,,
1,NaN,5.0,2.0,2.0,4.0,2.0,3.0,5.0,4.0,5.0,3.0,NaN,3.0,4.0,2.0,4.0,NaN,5.0,NaN,4.0
2,NaN,5.0,3.0,2.0,3.0,1.0,4.0,1.0,2.0,1.0,4.0,2.0,1.0,1.0,5.0,4.0,4.0,2.0,2.0,NaN
3,2.0,4.0,2.0,2.0,NaN,3.0,4.0,NaN,NaN,1.0,1.0,5.0,3.0,4.0,4.0,4.0,3.0,NaN,2.0,3.0
4,NaN,NaN,NaN,4.0,2.0,4.0,NaN,3.0,3.0,2.0,1.0,2.0,4.0,3.0,1.0,5.0,1.0,NaN,3.0,4.0
5,NaN,5.0,1.0,4.0,3.0,2.0,4.0,5.0,2.0,5.0,3.0,1.0,NaN,NaN,4.0,1.0,5.0,5.0,NaN,1.0
6,1.0,5.0,1.0,NaN,2.0,1.0,3.0,3.0,NaN,NaN,1.0,2.0,3.0,NaN,4.0,NaN,1.0,5.0,5.0,NaN
7,5.0,2.0,5.0,1.0,2.0,3.0,NaN,NaN,1.0,3.0,2.0,NaN,4.0,5.0,1.0,3.0,3.0,5.0,3.0,5.0
8,NaN,1.0,NaN,NaN,1.0,5.0,2.0,2.0,3.0,5.0,5.0,NaN,3.0,NaN,4.0,5.0,1.0,5.0,4.0,3.0
9,NaN,5.0,1.0,2.0,4.0,3.0,5.0,4.0,4.0,4.0,3.0,5.0,3.0,3.0,2.0,5.0,5.0,4.0,1.0,3.0
10,NaN,2.0,2.0,4.0,5.0,1.0,4.0,5.0,1.0,4.0,1.0,3.0,5.0,2.0,2.0,3.0,2.0,1.0,1.0,4.0